
CREATE TABLE port_calls_history (
  id SERIAL PRIMARY KEY,
  vessel_imo INTEGER NOT NULL REFERENCES vessels(imo) ON DELETE CASCADE,
  port_id CHARACTER VARYING NOT NULL,
  port_name CHARACTER VARYING NOT NULL,
  arrival TIMESTAMP WITH TIME ZONE NOT NULL,
  departure TIMESTAMP WITH TIME ZONE NOT NULL,
  is_insert BOOLEAN NOT NULL DEFAULT FALSE,
  is_update BOOLEAN NOT NULL DEFAULT FALSE,
  is_delete BOOLEAN NOT NULL DEFAULT FALSE,
  created_date TIMESTAMP WITH TIME ZONE NOT NULL,
  log_date TIMESTAMP WITH TIME ZONE NOT NULL
);